version: "3"
services:
  server_envio:
    image: server_envio_python
    ports:
      - "5001:5000"
    restart: always

  server_uav:
    image: server_uav_python
    ports: 
      - "5002:5000"
    restart: always

  front_end:
    image: uavfront
    ports: 
      - "4200:4200"
    restart: always
