version: "3.2"
services:

  db:
    image: mysql:8
    container_name: db
    ports:
        - "3306:3306"
    environment:
        MYSQL_USER: tcc
        MYSQL_PASSWORD: tcc
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: cpdlc2

  spring_boot_com_mysql:
    image: server-java:latest
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=prod
    links:
      - db

  # server_envio:
  #   image: server_envio_python:latest
  #   ports:
  #     - "5000:5000"
  #   restart: always

  # server_uav:
  #   image: server_uav_python:latest
  #   ports: 
  #     - "8085:8085"
  #   restart: always

  front_end:
    image: uavfront:latest
    ports: 
      - "4200:4200"
    restart: always
  
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq'
  #   ports:
  #       - 5672:5672
  #       - 15672:15672
    # networks:
    #     - rabbitmq_go_net

# networks:
#   rabbitmq_go_net:
#     driver: bridge